/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class ApiConfiguration {
<<<<<<< HEAD
  rootUrl: string = 'http://localhost:8045/api/v1';
=======
  rootUrl: string = 'http://localhost:8065/api/v1';
>>>>>>> e6f18f61c3d6cd2b5d2c79c823868cccfebe16bb
}

/**
 * Parameters for `ApiModule.forRoot()`
 */
export interface ApiConfigurationParams {
  rootUrl?: string;
}
